using System.Collections.Frozen;
using System.Numerics;

namespace Json2SharpLib.Common;

/// <summary>
/// Contains type aliases for multiple programming languages.
/// </summary>
internal static class TypeAliases
{
    /// <summary>
    /// Maps C# CLR types to their corresponding C# aliases.
    /// </summary>
    public static FrozenDictionary<Type, string> CSharpAliasTypes { get; } = new Dictionary<Type, string>()
    {
        [typeof(string)] = "string",
        [typeof(int)] = "int",
        [typeof(byte)] = "byte",
        [typeof(sbyte)] = "sbyte",
        [typeof(short)] = "short",
        [typeof(ushort)] = "ushort",
        [typeof(long)] = "long",
        [typeof(uint)] = "uint",
        [typeof(ulong)] = "ulong",
        [typeof(float)] = "float",
        [typeof(double)] = "double",
        [typeof(decimal)] = "decimal",
        [typeof(object)] = "object",
        [typeof(bool)] = "bool",
        [typeof(char)] = "char",
        [typeof(DateTime)] = nameof(DateTime),
        [typeof(TimeSpan)] = nameof(TimeSpan),
        [typeof(DateTimeOffset)] = nameof(DateTimeOffset),
        [typeof(Guid)] = nameof(Guid),
        [typeof(BigInteger)] = "BigInteger",

        [typeof(string[])] = "string[]",
        [typeof(int[])] = "int[]",
        [typeof(byte[])] = "byte[]",
        [typeof(sbyte[])] = "sbyte[]",
        [typeof(short[])] = "short[]",
        [typeof(ushort[])] = "ushort[]",
        [typeof(long[])] = "long[]",
        [typeof(uint[])] = "uint[]",
        [typeof(ulong[])] = "ulong[]",
        [typeof(float[])] = "float[]",
        [typeof(double[])] = "double[]",
        [typeof(decimal[])] = "decimal[]",
        [typeof(object[])] = "object[]",
        [typeof(bool[])] = "bool[]",
        [typeof(char[])] = "char[]",
        [typeof(DateTime[])] = nameof(DateTime) + "[]",
        [typeof(TimeSpan[])] = nameof(TimeSpan) + "[]",
        [typeof(DateTimeOffset[])] = nameof(DateTimeOffset) + "[]",
        [typeof(Guid[])] = nameof(Guid) + "[]",
        [typeof(BigInteger[])] = nameof(BigInteger) + "[]",

        [typeof(int?[])] = "int?[]",
        [typeof(byte?[])] = "byte?[]",
        [typeof(sbyte?[])] = "sbyte?[]",
        [typeof(short?[])] = "short?[]",
        [typeof(ushort?[])] = "ushort?[]",
        [typeof(long?[])] = "long?[]",
        [typeof(uint?[])] = "uint?[]",
        [typeof(ulong?[])] = "ulong?[]",
        [typeof(float?[])] = "float?[]",
        [typeof(double?[])] = "double?[]",
        [typeof(decimal?[])] = "decimal?[]",
        [typeof(bool?[])] = "bool?[]",
        [typeof(char?[])] = "char?[]",
        [typeof(DateTime?[])] = nameof(DateTime) + "?[]",
        [typeof(TimeSpan?[])] = nameof(TimeSpan) + "?[]",
        [typeof(DateTimeOffset?[])] = nameof(DateTimeOffset) + "?[]",
        [typeof(Guid?[])] = nameof(Guid) + "?[]",
        [typeof(BigInteger?[])] = nameof(BigInteger) + "?[]",
    }.ToFrozenDictionary();

    /// <summary>
    /// Maps C# CLR types to their corresponding Python aliases.
    /// </summary>
    public static FrozenDictionary<Type, string> PythonAliasTypes { get; } = new Dictionary<Type, string>()
    {
        [typeof(string)] = "str",
        [typeof(int)] = "int",
        [typeof(byte)] = "bytes",
        [typeof(sbyte)] = "bytes",
        [typeof(short)] = "int",
        [typeof(ushort)] = "int",
        [typeof(long)] = "int",
        [typeof(uint)] = "int",
        [typeof(ulong)] = "int",
        [typeof(float)] = "float",
        [typeof(double)] = "float",
        [typeof(decimal)] = "float",
        [typeof(object)] = "object",
        [typeof(bool)] = "bool",
        [typeof(char)] = "str",
        [typeof(Guid)] = "UUID",
        [typeof(TimeSpan)] = "timedelta",
        [typeof(DateTime)] = "datetime",
        [typeof(DateTimeOffset)] = "datetime",
        [typeof(BigInteger)] = "int",

        [typeof(string[])] = "list[str]",
        [typeof(int[])] = "list[int]",
        [typeof(byte[])] = "bytes",
        [typeof(sbyte[])] = "bytes",
        [typeof(short[])] = "list[int]",
        [typeof(ushort[])] = "list[int]",
        [typeof(long[])] = "list[int]",
        [typeof(uint[])] = "list[int]",
        [typeof(ulong[])] = "list[int]",
        [typeof(float[])] = "list[float]",
        [typeof(double[])] = "list[float]",
        [typeof(decimal[])] = "list[float]",
        [typeof(object[])] = "list[object]",
        [typeof(bool[])] = "list[bool]",
        [typeof(char[])] = "list[str]",
        [typeof(Guid[])] = "list[UUID]",
        [typeof(TimeSpan[])] = "list[timedelta]",
        [typeof(DateTime[])] = "list[datetime]",
        [typeof(DateTimeOffset[])] = "list[datetime]",
        [typeof(BigInteger[])] = "list[int]",

        [typeof(int?[])] = "Optional[list[int]]",
        [typeof(byte?[])] = "Optional[bytes]",
        [typeof(sbyte?[])] = "Optional[bytes]",
        [typeof(short?[])] = "Optional[list[int]]",
        [typeof(ushort?[])] = "Optional[list[int]]",
        [typeof(long?[])] = "Optional[list[int]]",
        [typeof(uint?[])] = "Optional[list[int]]",
        [typeof(ulong?[])] = "Optional[list[int]]",
        [typeof(float?[])] = "Optional[list[float]]",
        [typeof(double?[])] = "Optional[list[float]]",
        [typeof(decimal?[])] = "Optional[list[float]]",
        [typeof(bool?[])] = "Optional[list[bool]]",
        [typeof(char?[])] = "Optional[list[str]]",
        [typeof(Guid?[])] = "Optional[list[UUID]]",
        [typeof(TimeSpan?[])] = "Optional[list[timedelta]]",
        [typeof(DateTime?[])] = "Optional[list[datetime]]",
        [typeof(DateTimeOffset?[])] = "Optional[list[datetime]]",
        [typeof(BigInteger?[])] = "Optional[list[int]]",
    }.ToFrozenDictionary();

    /// <summary>
    /// Maps C# CLR types to their corresponding Java aliases.
    /// </summary>
    public static FrozenDictionary<Type, string> JavaAliasTypes { get; } = new Dictionary<Type, string>()
    {
        [typeof(string)] = "String",
        [typeof(int)] = "Integer",
        [typeof(byte)] = "byte",
        [typeof(sbyte)] = "byte",
        [typeof(short)] = "Short",
        [typeof(ushort)] = "Integer",
        [typeof(long)] = "Long",
        [typeof(uint)] = "Long",
        [typeof(ulong)] = "Long",
        [typeof(float)] = "Float",
        [typeof(double)] = "Double",
        [typeof(decimal)] = "Double",
        [typeof(object)] = "Object",
        [typeof(bool)] = "Boolean",
        [typeof(char)] = "String",
        [typeof(Guid)] = "UUID",
        [typeof(TimeSpan)] = "Duration",
        [typeof(DateTime)] = "OffsetDateTime",
        [typeof(DateTimeOffset)] = "OffsetDateTime",
        [typeof(BigInteger)] = "BigInteger",

        [typeof(string[])] = "List<String>",
        [typeof(int[])] = "List<Integer>",
        [typeof(byte[])] = "byte[]",
        [typeof(sbyte[])] = "byte[]",
        [typeof(short[])] = "List<Short>",
        [typeof(ushort[])] = "List<Integer>",
        [typeof(long[])] = "List<Long>",
        [typeof(uint[])] = "List<Long>",
        [typeof(ulong[])] = "List<Long>",
        [typeof(float[])] = "List<Float>",
        [typeof(double[])] = "List<Double>",
        [typeof(decimal[])] = "List<Double>",
        [typeof(object[])] = "List<Object>",
        [typeof(bool[])] = "List<Boolean>",
        [typeof(char[])] = "List<String>",
        [typeof(Guid[])] = "List<UUID>",
        [typeof(TimeSpan[])] = "List<Duration>",
        [typeof(DateTime[])] = "List<OffsetDateTime>",
        [typeof(DateTimeOffset[])] = "List<OffsetDateTime>",
        [typeof(BigInteger[])] = "List<BigInteger>",

        [typeof(int?[])] = "List<Integer>",
        [typeof(byte?[])] = "List<Byte>",
        [typeof(sbyte?[])] = "List<Byte>",
        [typeof(short?[])] = "List<Short>",
        [typeof(ushort?[])] = "List<Integer>",
        [typeof(long?[])] = "List<Long>",
        [typeof(uint?[])] = "List<Long>",
        [typeof(ulong?[])] = "List<Long>",
        [typeof(float?[])] = "List<Float>",
        [typeof(double?[])] = "List<Double>",
        [typeof(decimal?[])] = "List<Double>",
        [typeof(bool?[])] = "List<Boolean>",
        [typeof(char?[])] = "List<String>",
        [typeof(Guid?[])] = "List<UUID>",
        [typeof(TimeSpan?[])] = "List<Duration>",
        [typeof(DateTime?[])] = "List<OffsetDateTime>",
        [typeof(DateTimeOffset?[])] = "List<OffsetDateTime>",
        [typeof(BigInteger?[])] = "List<BigInteger>",
    }.ToFrozenDictionary();
}